[versions]
agp = "9.3.2"
cxx = "29.0.14206865"
hiddenapibypass = "6.1"

[libraries]
cxx = { group = "org.lsposed.libcxx", name = "libcxx", version.ref = "cxx" }
hiddenapibypass = { group = "org.lsposed.hiddenapibypass", name = "hiddenapibypass", version.ref = "hiddenapibypass" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
