name: Android CI

on:
  push:
    branches: inject_s
    paths-ignore:
      - '**.md'
      - '.github/workflows/autopif.yml'
  pull_request:
    branches: inject_s
    paths-ignore:
      - '**.md'
      - '.github/workflows/autopif.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ (github.actor == 'jiugjk' && github.repository_owner == 'jiugjk') && fromJSON('["self-hosted", "fast-tmpfs"]') || 'ubuntu-latest' }}

    steps:
    - name: Check out
      uses: actions/checkout@v7
      with:
        submodules: 'recursive'
        fetch-depth: 1
        ref: inject_s

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Setup pnpm
      uses: pnpm/action-setup@v6
      with:
        version: 'latest'

    - name: Setup Node
      uses: actions/setup-node@v7
      with:
        node-version: 'lts/*'
        cache: 'pnpm'
        cache-dependency-path: webui/pnpm-lock.yaml

    - name: Build WebUI
      run: |
        cd webui
        pnpm install --frozen-lockfile
        pnpm run build

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease zip

    - name: Assert module artifacts
      run: |
        test -f module/webroot/index.html
        test -f module/classes.dex
        ls module/zygisk/*.so
        test -f out/PlayIntegrityFix.zip

    - name: Setup variables
      run: |
        VERSION=$(jq -r '.version' update.json)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Upload CI module zip
      uses: actions/upload-artifact@v7
      with:
        name: PlayIntegrityFix_${{ env.VERSION }}_${{ github.run_number }}
        path: out/PlayIntegrityFix.zip
        compression-level: 9
